### ISSUE TITLE
ffmpeg compilation fails, but can link against my own ffmpeg build

### ISSUE THREAD

**Issue by Geremia** [Sammyboy/omxplayer-SlackBuild#2]
I was not able use your script to compile oxmplayer with in the "in-house" ffmpeg:
```
/bin/sh: -c: line 4: unexpected EOF while looking for matching `"'
/bin/sh: -c: line 223: syntax error: unexpected end of file
make[1]: *** [Makefile.ffmpeg:19: configure] Error 1
make[1]: Leaving directory '/tmp/SBo/omxplayer-git_ecd446d'
make: *** [Makefile:82: ffmpeg] Error 2
```

But I was able to compile omxplayer against my local build of ffmpeg.

The ability not to build ffmpeg and link against an already-built ffmpeg would be a good feature to add to your SlackBuild.

diff of my changes to your script:
```diff
diff --git a/omxplayer.SlackBuild b/omxplayer.SlackBuild
index 3faefd8..21865e3 100755
--- a/omxplayer.SlackBuild
+++ b/omxplayer.SlackBuild
@@ -156,6 +156,8 @@ sed -e 's/#arm-unknown-linux-gnueabi-strip/arm-unknown-linux-gnueabi-strip/g;' \
     -e 's|arm-linux-gnueabihf/||' \
     -e 's/CFLAGS=.*/include Makefile.include/' \
     -e 's|-I/usr/include/freetype2.*||' \
+    -e '/cp -P ffmpeg_compiled/d' \
+    -e 's|ffmpeg_compiled||g' \
     -i Makefile
 
 which ronn &> /dev/null && \
@@ -178,7 +180,6 @@ EOF
   read -r REPLY
 }
 
-make ffmpeg
 make
 make dist DIST=$PKG
```
I don't think `rubygem-ronn` is a dependency; I don't have it and could still build.
<sub>With your SlackBulid, I didn't have to add some dbus includes directories, like I did before.</sub><hr>Also, you should [submit your script to SlackBuilds](https://slackbuilds.org/submit/). I'm surprised omxplayer isn't up there yet.

**Comment by Geremia** [comment]
I fixed the ffmpeg building issue:
```diff
diff --git a/omxplayer.SlackBuild b/omxplayer.SlackBuild
index 3faefd8..51efab9 100755
--- a/omxplayer.SlackBuild
+++ b/omxplayer.SlackBuild
@@ -135,9 +135,8 @@ INCLUDES  += -I/opt/vc/include/interface/vcos/pthreads \
              -I/usr/include/freetype2
 EOF
 
-sed -e '/--enable-cross-compile/d;' \
-    -e '/--cross-prefix/d;' \
-    -e 's/-j$(shell nproc) //g;' \
+sed -e 's/-j$(shell nproc) //g;' \
+    -e 's/--extra-cflags="/\0"/' \
     -i Makefile.ffmpeg
 
 sed -e 's/$(HOST)-//g;' \
@@ -178,9 +177,9 @@ EOF
   read -r REPLY
 }
```
There was an unmatched double-quote in Makefile.ffmpeg. And I needed cross-compiling enabled.

**Comment by asarangan** [comment]
I see that this issue is over a year old, but the git archive still seems to contain the buggy version. I am not all that familiar with how to run patch, but I copied over the archive using 
git clone https://github.com/Sammyboy/omxplayer-SlackBuild.git
Then I ran ./omxplayer.SlackBuild. I got the same unmatched quote error.

**Comment by Sammyboy** [comment]
I made an update, fixing issues and adding new features. See README file.
